### ISSUE TITLE
Styling_in_QML: Unable to input text in the loginForm

### ISSUE THREAD

**Issue by gserm** [PacktPublishing/Qt5-CPP-GUI-Programming-Cookbook-Second-Edition#1]
Running the Chapter01/Styling_in_QML code presents the login interface as expected, but it doesn't let the user actually input any characters in the username (textInput1) and password (textInput2) fields.

**Comment by leezhieng** [comment]
> Running the Chapter01/Styling_in_QML code presents the login interface as expected, but it doesn't let the user actually input any characters in the username (textInput1) and password (textInput2) fields.

The text input is hidden behind the rectangle shape which is its child object. Older Qt version seems to place all children objects behind its parent; but newer Qt places the children in-front, causing the text input to be hidden. I have fixed it by setting the Z order of the rectangles to be -1 to force it go behind the text input.
