### ISSUE TITLE
Signals_Slots: no matching function for call to information

### ISSUE THREAD

**Issue by gserm** [PacktPublishing/Qt5-CPP-GUI-Programming-Cookbook-Second-Edition#2]
Chapter02/Signals_Slots fails to compile with the error: 
no matching function for call to 'information'
        QMessageBox::information(this, "Hello", "Button has been clicked!");
        ^~~~~~~~~~~~~~~~~~~~~~~~

I believe the reason for this is the fact that `MyClass` (the `this` pointer in the above error) inherits from `QObject` but the `information` method expects a `QWidget`, hence the error.

**Comment by leezhieng** [comment]
> Chapter02/Signals_Slots fails to compile with the error:
> no matching function for call to 'information'
> QMessageBox::information(this, "Hello", "Button has been clicked!");
> ^~~~~~~~~~~~~~~~~~~~~~~~
> 
> I believe the reason for this is the fact that `MyClass` (the `this` pointer in the above error) inherits from `QObject` but the `information` method expects a `QWidget`, hence the error.

Fixed. I changed 'this' to 'nullptr'.
