### ISSUE TITLE
Graphics_Painter_in_Qt: Tux image not showing

### ISSUE THREAD

**Issue by gserm** [PacktPublishing/Qt5-CPP-GUI-Programming-Cookbook-Second-Edition#3]
The image of the tux is not shown on the window. I tried giving the full path of the image, but that didn't work either.

**Comment by leezhieng** [comment]
> The image of the tux is not shown on the window. I tried giving the full path of the image, but that didn't work either.

If you're running your project from Qt Creator, then the tux image has to be placed in the build folder (outside release or debug folder). That's how Qt Creator works. If you run the executable directly (not from Qt Creator) then the tux image has to be in the same folder as the executable. I'm running Windows here and it works this way. Do let me know if it works the same in MacOS.

**Comment by leezhieng** [comment]
If it still doesn't work in MacOS, the alternative solution is to place the image in a Qt resource file (.qrc)

**Comment by PhilCRose** [comment]
Create a Resource file, and add the image. I created images and put Tux in there. Then in the code:
image.load(":/images/tux.png");

**Comment by leezhieng** [comment]
Make sure the file name and extension is correct. You can also try use
qrc:///images/tux.png instead of just :/images/tux.png
