### ISSUE TITLE
Coordinate_Transformation: connect timer with MainWindow fails

### ISSUE THREAD

**Issue by gserm** [PacktPublishing/Qt5-CPP-GUI-Programming-Cookbook-Second-Edition#4]
The `connect` call in the `MainWindow` constructor:
`connect(timer, QTimer::timeout, this, MainWindow::update);`
fails to compile with:
call to non-static member function without an object argument

I can only make it work using the old syntax:
`connect(timer, SIGNAL(timeout()), this, SLOT(update()));`

**Comment by leezhieng** [comment]
> The `connect` call in the `MainWindow` constructor:
> `connect(timer, QTimer::timeout, this, MainWindow::update);`
> fails to compile with:
> call to non-static member function without an object argument
> 
> I can only make it work using the old syntax:
> `connect(timer, SIGNAL(timeout()), this, SLOT(update()));`

Thanks for the report. Apparently there are multiple functions that are called update(), so I believe it made Qt confuse and didn't know which update() function you're talking about here, hence the error. I have fixed the code by adding an updateWindow() function that calls the connect update() function. This is a quick hack, I'm not sure if Qt developers are aware of this issue or not.

**Comment by leezhieng** [comment]
> The `connect` call in the `MainWindow` constructor:
> `connect(timer, QTimer::timeout, this, MainWindow::update);`
> fails to compile with:
> call to non-static member function without an object argument
> 
> I can only make it work using the old syntax:
> `connect(timer, SIGNAL(timeout()), this, SLOT(update()));`

Thanks for the report. Apparently there are multiple functions that are called update(), so I believe it made Qt confuse trying to connect to the update() function that is not a slot, hence the error. I have fixed the code by adding an updateWindow() function that calls the correct update() function. This is a quick hack, I'm not sure if Qt developers are aware of this issue or not.

**Comment by gserm** [comment]
The hack works great, thank you!
