### ISSUE TITLE
Setup OpenGL: triangle not shown on middle of screen

### ISSUE THREAD

**Issue by gserm** [PacktPublishing/Qt5-CPP-GUI-Programming-Cookbook-Second-Edition#5]
When running the "Setup OpenGL" project, the triangle doesn't appear on the centre of the window as shown in the book. I'm using MacOS with the latest version of Qt installed. Any help would be appreciated!
<img width="715" alt="Screenshot 2019-11-04 at 16 31 47" src="https://user-images.githubusercontent.com/29985703/68138547-adb70580-ff20-11e9-915a-6189937ff5b5.png">

**Comment by leezhieng** [comment]
> When running the "Setup OpenGL" project, the triangle doesn't appear on the centre of the window as shown in the book. I'm using MacOS with the latest version of Qt installed. Any help would be appreciated!
> <img alt="Screenshot 2019-11-04 at 16 31 47" width="715" src="https://user-images.githubusercontent.com/29985703/68138547-adb70580-ff20-11e9-915a-6189937ff5b5.png">

I have added retina scale to glViewport, let me know if it solve your problem. Thanks.

**Comment by gserm** [comment]
Thank you, this did the trick!
